#!/bin/sh

top_dir=$1
echo "TOPDIR = " $top_dir

# check if svn info available (do not write anything)
git remote -v 2> /dev/null > /dev/null

if [ $? = 0 ] ; then
# svn info available: get svn revision
   git_rev=$(git describe)
else
# svn info available: revert to no info
   git_rev=unknown
fi
echo "GITREV = " $git_rev

# write svn into file version_tmp.f90
cat west_version.f90.in | sed "s/unknown/$git_rev/;s&unset&$top_dir&" > west_version.f90.tmp

# check if a previous version.f90 file exists
if test -f west_version.f90 ; then

# version.f90 existing: check if new and previous files differ
   diff -wib west_version.f90.tmp west_version.f90  2> /dev/null > /dev/null

   if [ $? = 1 ] ; then
# they differ: update file version.f90
      mv west_version.f90.tmp west_version.f90
   else
# do not update if files are the same (prevents useless recompilation)
      rm west_version.f90.tmp 
   fi
else

# file version.f90 not existing: create one
   mv west_version.f90.tmp west_version.f90

fi
