# Makefile for Westpy

include ../../make.inc

all : title copy

copy:
	- /bin/cp westpy.py ../../bin

clean :
	- /bin/rm -f ../../bin/westpy.py

title :
	@echo "                  "
	@echo "##################"
	@echo "#### WESTpy ######"
	@echo "##################"
	@echo "                  "

