#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "  This example shows how to run a GW simulation for the SiH4 molecule"

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x wstat.x wfreq.x"
PSEUDO_LIST="Si.pz-vbc.UPF H.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "  Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
WSTAT_COMMAND="$PARA_PREFIX $BIN_DIR/wstat.x $PARA_POSTFIX"
WFREQ_COMMAND="$PARA_PREFIX $BIN_DIR/wfreq.x $PARA_POSTFIX"

$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"

cat > scf.in << EOF
&control
 calculation  = 'scf'
 restart_mode = 'from_scratch'
 pseudo_dir   = '$PSEUDO_DIR/'
 outdir       = '$TMP_DIR/'
 prefix       = 'sih4'
 wf_collect   = .TRUE.
/
&system
 ibrav     = 1
 celldm(1) = 20
 nat       = 5
 ntyp      = 2
 ecutwfc   = 25.0
 nbnd      = 10
/
&electrons
 conv_thr = 1.d-12
 diago_full_acc = .TRUE.
/
ATOMIC_SPECIES
Si 28.0855   Si.pz-vbc.UPF
H  1.00794   H.pz-vbc.UPF
ATOMIC_POSITIONS angstrom
Si      0.0000   0.0000  0.0000
H       0.8544   0.8544  0.8544
H      -0.8544  -0.8544  0.8544
H      -0.8544   0.8544 -0.8544
H       0.8544  -0.8544 -0.8544
K_POINTS {gamma}
EOF

$ECHO "  computing the KS-DFT electronic structure for SiH4...\c"
$PW_COMMAND < scf.in > scf.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "  running wstat.x as: $WSTAT_COMMAND"

cat > wstat.in << EOF
&input_west
 qe_prefix   = 'sih4',
 west_prefix = 'sih4',
 outdir      = '$TMP_DIR/',
/
&wstat_control
 wstat_calculation = 'S'
 n_pdep_eigen      = 10
 trev_pdep         = 1.d-5 
/
EOF

$ECHO "  computing the static screening for SiH4...\c"
$WSTAT_COMMAND < wstat.in > wstat.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "  running wfreq.x as: $WFREQ_COMMAND"

cat > wfreq.in << EOF
&input_west
 qe_prefix   = 'sih4',
 west_prefix = 'sih4',
 outdir      = '$TMP_DIR/',
/
&wstat_control
 wstat_calculation = 'S'
 n_pdep_eigen      = 10
 trev_pdep         = 1.d-5 
/
&WFREQ_CONTROL
 wfreq_calculation    = "XWGQ"
 n_pdep_eigen_to_use  = 10
 qp_bandrange(1)      = 1
 qp_bandrange(2)      = 2
 macropol_calculation = "N"
 n_lanczos            = 30
 n_imfreq             = 100
 n_refreq             = 100
 ecut_imfreq          = 120.0
 ecut_refreq          = 3.0
 n_secant_maxiter     = 7
/
EOF

$ECHO "  computing the GW electronic structure for SiH4...\c"
$WFREQ_COMMAND < wfreq.in > wfreq.out
check_failure $?
$ECHO " done"

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/sih4*
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
